### ISSUE TITLE
Install with Homebrew

### ISSUE THREAD

**Issue by brianstrauch** [brianstrauch/spotify-cli#18]

**Comment by irateswami** [comment]
Mind if I help? I've been meaning to learn how to do brew formulae

**Comment by brianstrauch** [comment]
@irateswami Sure, feel free!

**Comment by irateswami** [comment]
Awesome. Typically brew formulae are in a separate repo, I'll make one and add you on it.

**Comment by TomTucka** [comment]
any update on this? Setting up homebrew is super easy with goreleaser!

**Comment by brianstrauch** [comment]
I agree; @TomTucka would you like to take this issue? If not, I'll take a stab at it later today

**Comment by irateswami** [comment]
Busy week at work, here's what I have so far: 

`SPOTIFY_CLI_VERSION= "v1.8.0".freeze

class Spotifycli < Formula
  desc "A Spotify CLI"
  homepage "https://github.com/brianstrauch/spotify-cli"
  version "1.8.0"
  if OS.mac && Hardware::CPU.intel?
    sha256 ""
    url "https://github.com/brianstrauch/spotify-cli/releases/download/#{version}/spotify-cli_#{version}_darwin_amd64"
  elsif OS.mac && Hardware::CPU.arm?
    sha256 ""
    url "https://github.com/brianstrauch/spotify-cli/releases/download/#{version}/spotify-cli_#{version}_darwin_arm64"
  end

  def install
    if OS.mac?
      mv "spotify-cli_#{version}_darwin_amd64", "spotify-cli"
    elsif OS.linux?
      mv "spotify-cli_#{version}_linux_amd64", "spotify-cli"
    end
    bin.install "spotify-cli"
  end
  test do
    #system "#{bin}/dry", "--version"
  end
end
`

**Comment by TomTucka** [comment]
> I agree; @TomTucka would you like to take this issue? If not, I'll take a stab at it later today

@brianstrauch Yep, I can update the goreleaser file later today.
