### ISSUE TITLE
EOF

### ISSUE THREAD

**Issue by patrickhener** [brianstrauch/spotify-cli#23]
I mean, I am not quite sure if I am doing right but no matter what I do (after login) it just says "Error: EOF". So, not working for me.

**Comment by brianstrauch** [comment]
It looks like there was a breaking change to the Spotify API either yesterday or the day before. That error most likely means that you don't have an instance of Spotify running. Either open the web app or the desktop app and it should work! I'll keep this issue open while I'm investigating the issue

**Comment by patrickhener** [comment]
Additonally after starting a session (on my mobile playing a song) commands did "something". But play, pause, next,... did not seam to do anything. Just wanted to also let you know.

**Comment by brianstrauch** [comment]
@patrickhener Fixed! You can use `spotify update` to get the improved version.
