### ISSUE TITLE
Set up CI with version auto-updating

### ISSUE THREAD

**Issue by brianstrauch** [brianstrauch/spotify-cli#30]
- [X] Set up CI
- [ ] Version auto-updating

A commit with a new version number in `main.go` should trigger a release.

**Comment by OrlovEvgeny** [comment]
Hi
Goreleaser is able to automatically update the version of the application when we make a new tag (see **ldflags** https://goreleaser.com/customization/build/).
Well, we can just create and push new tag, goreleaser will do the rest for us
