### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by jorgeAM** [brianstrauch/spotify-cli#37]
Hello!

I've tried to login but when accept permission, redirect a `localhost` url

![Captura de Pantalla 2021-07-07 a la(s) 17 05 48](https://user-images.githubusercontent.com/19254966/124834582-a04bed00-df45-11eb-9e70-d1fe22537a56.png)

and in my apps tab spotify cli  is shown

![Captura de Pantalla 2021-07-07 a la(s) 17 07 48](https://user-images.githubusercontent.com/19254966/124834734-ddb07a80-df45-11eb-8c7a-c90031471539.png)

I've already tried to remove app and try again, the problem is still there

Hope you can help me!

**Comment by brianstrauch** [comment]
Hmm... that's the correct URL. Not sure what the issue is; so here are a few questions:
* Does the CLI show any errors?
* Are you using windows?
* Do you have Spotify premium?

**Comment by jorgeAM** [comment]
- No, but keeps freeze, I have to cut proccess with ctrl + C
-  No, I'm using MacOS
- Yes

I don't know if this is correct but redict show me this 

![Captura de Pantalla 2021-07-07 a la(s) 17 18 42](https://user-images.githubusercontent.com/19254966/124835722-624fc880-df47-11eb-81b7-bd9a4070c92e.png)

**Comment by brianstrauch** [comment]
This is the function that's failing: https://github.com/brianstrauch/spotify-cli/blob/7dccf57bf98b7a774dbed9c93afc1f7d7115b6f5/internal/login/login.go#L108-L131

Do you have something running on port 1024?

**Comment by jorgeAM** [comment]
I dont ...

**Comment by jorgeAM** [comment]
My problem was that my browser (Chrome) redirect to use HTTPS instead HTTP
