### ISSUE TITLE
Error: Player command failed: No active device found

### ISSUE THREAD

**Issue by juanfgarcia** [brianstrauch/spotify-cli#38]
When I try to play music I get the error:
```
Error: Player command failed: No active device found
```
Probably because I have more than one device connected to Spotify.

Searching on google I've found:  https://github.com/spotify/web-api/issues/1325 which suggest to make the request with 
`https://api.spotify.com/v1/me/player/play?device_id="+this._device_id`

I've been looking on the source code to add this option, but I have no experience with cobra and I also don't know where the request is made to test if this change could work. Could you tell me where I can change it? So I can report if that change works for me (and hope for other users with more than one device)

**Comment by brianstrauch** [comment]
I'll take a look at this soon, but we might be able to make a `spotify devices` command that shows devices and their IDs, as well as a `spotify play --device_id` flag.

**Comment by brianstrauch** [comment]
In the meantime, you should be able to start a session (open spotify and start playing music) and the CLI should work fine.

**Comment by juanfgarcia** [comment]
> but we might be able to make a spotify devices command that shows devices and their IDs, as well as a spotify play --device_id flag.

Yes that's right, but I mean that I can try to hardcode the URL with my device ID to see if that solves the issue, before to start coding the new commands.

> you should be able to start a session (open spotify and start playing music) and the CLI should work fine.

Yes that works.

**Comment by brianstrauch** [comment]
@juanfgarcia I've implemented both commands on the `master` branch, but I think we might also need to call https://developer.spotify.com/documentation/web-api/reference/#endpoint-transfer-a-users-playback for your use case.

**Comment by juanfgarcia** [comment]
Now `devices list` serves the displays id's. But `play --device-id` still giving the same error until you play the song in the Spotify app. 

Your suggestion about transferring the users playback sounds good. Let me know if you implement it so I can check.
