### ISSUE TITLE
Conflict with spotify on Windows10

### ISSUE THREAD

**Issue by PIndividual** [brianstrauch/spotify-cli#44]
Whatever command I use, it pulls up the Spotify for windows application instead of spotify-cli.

**Comment by PIndividual** [comment]
I tried disabling the original spotify response inside the windows settings, but here are the responses
![image](https://user-images.githubusercontent.com/62368342/147656732-ff6296c4-50b1-4f7e-b59e-9cda81cc5585.png)
seems that spotifycli cannot link with my system automatically.

**Comment by brianstrauch** [comment]
Hi, it looks like you're trying to run a command called "spotifycli", but the Windows executable for this project is called "spotify.exe". If the name "spotify" is causing conflicts with the Spotify desktop client, try removing the desktop client from your $PATH, and adding the CLI client.

**Comment by Nycz-lab** [comment]
u should use the complete filename of the exe inlcuding '.exe' also maybe u should switch to the spotify application from their website instead of the one in the windows store
