### ISSUE TITLE
Incomplete installation information

### ISSUE THREAD

**Issue by psomdeb25** [brianstrauch/spotify-cli#45]
Hello @brianstrauch. I downloaded the amd version of the spotify-cli from the link you provided in the README section. However, there is no further instruction as to how to install it on my system (macOS 12.0.1). Would it be possible to have detailed instructions on the installation?

Thank you very much!

**Comment by brianstrauch** [comment]
Hi, thanks for opening an issue! Ideally, I'd like to make the CLI available to download via Homebrew (there's already an issue for this, #18).

In the meantime, try the following:
```
% mv spotify-cli_1.12.0_darwin_amd64 /usr/local/bin/spotify
% chmod +x /usr/local/bin/spotify
```

System Preferences > Security & Privacy > General > Allow Anyway

```
% spotify version
v1.12.0
```
