### ISSUE TITLE
Does this require spotify premium to work?

### ISSUE THREAD

**Issue by Zopenzop** [brianstrauch/spotify-cli#47]
I can see the status of my account, the current playing song and so on. But none of the commands actually work. The play pause commands don't have any effect on the Spotify app. Pausing does show "Paused ..." in command prompt but spotify doesn't pause.

**Comment by brianstrauch** [comment]
From the following thread, it looks like premium may be required: https://community.spotify.com/t5/Spotify-for-Developers/Developers-Player-API-No-mention-about-the-Spotify-Premium/td-p/5217868
